---
title: "Slot Machine"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## First

[**7/23/20:slotmachine1.R**](../R/slotmachine1.R): First, I wrote a function to generate 3 symbols to simulate the rolling of a slot matchine: `get_symbols()`, which contains the list `wheel()`, by using the `sample()` function. The next segment is a frame for how the slot machine will operate through the use of if, else if, and else functions. The `same()` function checks for a row of three. The next part deals with the rolling of bars with `else if`. Then, I wrote code on how these two would be given payout. The next segment is dealing with rolling of "C", otherwise known as cherries in a casino. The final part is dealing with the rolling of diamonds, which can double the prize. 
```{r slotmachine1}
source("../R/slotmachinefinal.R")
play <- function() {
  symbols <- get_symbols()
  print(symbols)
  score(symbols)
}
play()
```

## Second

[**7/24/20:slotmachine2.R**](../R/slotmachine2.R): The purpose of this is to delve deeper into the slot machine script produced in slotmachine1.R. First, I worked with attributes by assigning one_play a vector. Attributes is meant to make the play function less redundant; I removed the `print()` function. I then wrote a new function to display slot results, `slot_display()`. The last line in the function, `cat(string)` will replace `\n` with a new line. Essentially, `slot_display()` will clean up the output, tidying it up.
```{r slotmachine2}
source("../R/slotmachine2.R")
slot_display <- function(prize) {
  symbols <- attr(one_play, "symbols")
  symbols <- paste(symbols, collapse = " ")
  prize <- one_play
  string <- paste(symbols, prize, sep = "\n$")
  cat(string)
}
slot_display(play())
```
I then worked with a new print method to modify `one_play` to do what `slot_display()` did.
```{r slotmachine2 2}
source("../R/slotmachine2.R")
print.slots <- function(x, ...) {
  slot_display(x)
}
one_play
```

## Third

[**7/28/20:slotmachine3.R**](../R/slotmachine3.R): The purpose of this is to utilize the `score()` function I wrote before and apply it to realistic scenarios through statistics. I first used `expand.grid` to construct a data frame. I then added probabilites of Var 2, 3, and 3 as combos to columns. Using the application of statistics, I calculated the probability of every possible combination of the slot machine. Summing up these probabilities produces the expected 1. Then, through the use of loops, I can calculate the prize of every combination. Loops utilize `for()` to execute code. Then, finally, I calculated the expected value of the prize.
```{r slotmachine3}
source("../R/slotmachine3.R")
combos <- expand.grid(wheel, wheel, wheel, stringsAsFactors = FALSE)

prob <- c("DD" = .03, "7" = .03, "BBB" = .06, "BB" = .1, "B" = .25, "C" = .01, "0" = .52)

combos$prob1 <- prob[combos$Var1]
combos$prob2 <- prob[combos$Var2]
combos$prob3 <- prob[combos$Var3]

head(combos, 3)
```